### ISSUE TITLE
can't create addresses with leading slash

### ISSUE THREAD

**Issue by grs** [EnMasseProject/admin#20]
e.g. /telemetry/DEFAULT_TENANT/xy

If you put such an address in an address list and post it, it fails silently to create that address and any after it. Looks like it may be related to the char conversion:

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/myproject/configmaps. Message: ConfigMap "address-config--telemetry-default-tenant-xy" is invalid: metadata.labels: Invalid value: "-telemetry-default-tenant-xy": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "-telemetry-default-tenant-xy": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=ConfigMap, name=address-config--telemetry-default-tenant-xy, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=ConfigMap "address-config--telemetry-default-tenant-xy" is invalid: metadata.labels: Invalid value: "-telemetry-default-tenant-xy": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:741)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:403)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation$2.apply(BaseOperation.java:372)
	at io.fabric8.kubernetes.api.model.DoneableConfigMap.done(DoneableConfigMap.java:26)
	at enmasse.controller.address.api.DestinationApiImpl.createOrReplace(DestinationApiImpl.java:108)
	at enmasse.controller.address.api.DestinationApiImpl.createDestination(DestinationApiImpl.java:79)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at enmasse.controller.api.v3.AddressApiHelper.putAddresses(AddressApiHelper.java:40)
	at enmasse.controller.api.v3.http.AddressingServiceBase.putAddresses(AddressingServiceBase.java:32)
	at enmasse.controller.api.v3.http.AddressingService.putAddresses(AddressingService.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.plugins.server.vertx.RequestDispatcher.service(RequestDispatcher.java:93)
	at org.jboss.resteasy.plugins.server.vertx.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:65)
	at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:198)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406)
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:666)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lulf** [comment]
Thanks for the detailed report.

This is a restriction imposed on kubernetes labels. I will replace the use of labels with annotations in cases like this, since we don't really need to lookup the address by key a lot, and in the cases we do, the number of addresses to iterate through is likely to be within manageable range.
